when:
  branch:
    - main
  event: push

steps:
  release:
    when:
      repo: gillesvink/none
    image: rust
    commands:
      - apt update && apt install protobuf-compiler -y
      - curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
      - cargo binstall release-plz
      - export CARGO_REGISTRY_TOKEN=$${CARGO_REGISTRY_TOKEN}
      - git config user.name "git log -1 --pretty=format:'%an'"
      - git config user.email '${CI_COMMIT_AUTHOR_EMAIL}'
      - git remote set-url origin https://$${CODEBERG_TOKEN}@codeberg.org/gillesvink/opendefocus.git
      - release-plz release --forge gitea --git-token $${CODEBERG_TOKEN}
    environment:
      CODEBERG_TOKEN:
        from_secret: codeberg_token
      CARGO_REGISTRY_TOKEN:
        from_secret: cargo_registry_token

  pull_request:
    image: rust
    commands:
      - curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
      - cargo binstall release-plz
      - git config user.name "git log -1 --pretty=format:'%an'"
      - git config user.email '${CI_COMMIT_AUTHOR_EMAIL}'
      - git remote set-url origin https://$${CODEBERG_TOKEN}@codeberg.org/gillesvink/opendefocus.git
      - release-plz release-pr --forge gitea --git-token $${CODEBERG_TOKEN}
    environment:
      CODEBERG_TOKEN:
        from_secret: codeberg_token

depends_on:
  - test
